# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 52ed204302e7a39c8a9882a3abd573d214856cd9be9aee6927387b37eac3407632491339ca07c789971d610b4fd8cb740373b2101796d4df096d58815effd9b9

test:
  secret_key_base: 151d0988562bb1eb40145b6e853499b80d5c85067b5039df34a0d7cad2365b2bc12f8e706b7260cdb89b251e73f70bef5df9cee24ecb0c9475302086fd235105

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
